name: scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: checkout scripts
      uses: actions/checkout@v3
      with:
        path: scripts
    - name: checkout shared
      uses: actions/checkout@v3
      with:
        repository: DanielEgbers/Actions.Shared
        path: Actions.Shared
    - name: checkout data
      env:
        DATA_REPO: ${{ secrets.DATA_REPO }}
      run: |-
        git clone $DATA_REPO data
    - name: setup
      run: |-
        dotnet tool update --global dotnet-script
        dotnet script --info
    - name: prepare
      run: |-
        dotnet script --debug scripts/actions.csx -- --help
    - name: scrape
      env:
        WOCHENPLAN_URL: ${{ secrets.WOCHENPLAN_URL }}
      run: |-
        dotnet script scripts/actions.csx scrape
    - name: push
      run: |-
        dotnet script scripts/actions.csx push
    - name: get status date
      id: status_date
      run: |-
        echo "::set-output name=date::$(date +'%A %Y-%m-%d %H:%M:%S')"
    - name: find status comment
      uses: peter-evans/find-comment@v2
      id: find_comment
      with:
        issue-number: ${{ vars.STATUS_ISSUE_ID }}
        comment-author: 'github-actions[bot]'
        body-includes: ${{ vars.STATUS_ISSUE_COMMENT_TITLE }}
    - name: update status comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ vars.STATUS_ISSUE_ID }}
        comment-id: ${{ steps.find_comment.outputs.comment-id }}
        edit-mode: replace
        body: |
          ## ${{ vars.STATUS_ISSUE_COMMENT_TITLE }}
          ${{ steps.status_date.outputs.date }}
